apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  api-key: {{ .Values.secrets.apiKey | quote }}
  username: {{ .Values.secrets.basicAuth.username | quote }}
  password: {{ .Values.secrets.basicAuth.password | quote }}

